#!/usr/bin/env node
/**
 * Generate `test/audit/README.md` — an index of the audit findings the tests
 * under `test/audit/` pin.
 *
 * #71 landed ~80 files whose names cite audit finding IDs (`A1`, `B-F2`,
 * `G-F8`, `N3`, `O5`). Those IDs were defined in reports that live on one
 * person's machine, so a maintainer meeting `regression-CF4-btc-pending-
 * outgoing.test.ts` had no way to learn what C-F4 was, what the pre-fix
 * behaviour looked like, or which commit closed it (#75).
 *
 * The reports are not needed. Every one of those files already documents its
 * own finding — in a block comment, or failing that in its `describe` title —
 * so the index is derived from the repository rather than from anything
 * private. That also means it cannot disclose more than the tests already do.
 *
 * `--check` regenerates and diffs instead of writing, so the index cannot rot
 * the way the thing it documents did.
 */

import fs from 'node:fs'
import path from 'node:path'
import { execFileSync } from 'node:child_process'

const root = path.resolve(import.meta.dirname, '..')
const auditDir = path.join(root, 'test/audit')
const outPath = path.join(auditDir, 'README.md')

/** `regression-<ID>-slug.test.ts` / `probe-<TASK>-slug.test.ts`. */
const NAME = /^(regression|probe)-([A-Z]+[0-9]*(?:-[A-Z]+[0-9]+)*)-(.+)\.test\.ts$/

/** Strip the leading "Audit finding X —" boilerplate; it is the table's key. */
function stripLead(text) {
  return text
    .replace(/^(Audit findings?|AUDIT|Regression test for audit finding|TASK [A-Z])\s*/i, '')
    .replace(/^[A-Z]?-?[A-Z]*[0-9]*(\s*\+\s*[A-Z0-9-]+)?\s*\(?[^)]*\)?\s*[—:-]\s*/, '')
    .trim()
}

/** One sentence describing the finding: block comment first, else `describe`. */
function summarize(text) {
  const comment = text.match(/\/\*\*?([\s\S]*?)\*\//)
  if (comment) {
    const body = comment[1]
      .split('\n')
      .map((l) => l.replace(/^\s*\*\s?/, '').trim())
      .filter(Boolean)
      .join(' ')
    const first = splitFirstSentence(stripLead(body))
    if (first.length >= 30) return first
  }
  const describe = text.match(/describe(?:\.\w+)?\(\s*['"`]([^'"`]+)/)
  if (describe) {
    const first = splitFirstSentence(stripLead(describe[1]))
    if (first) return first
  }
  return ''
}

function splitFirstSentence(s) {
  return s.split(/(?<=[.;])\s/)[0].replace(/\s+/g, ' ').trim()
}

/** The commit that ADDED the test — when the finding was closed. */
function addedIn(file) {
  try {
    const out = execFileSync(
      'git',
      ['log', '--diff-filter=A', '--format=%h', '--', path.join('test/audit', file)],
      { cwd: root, encoding: 'utf8' },
    )
    return out.trim().split('\n').filter(Boolean).pop() ?? ''
  } catch {
    return ''
  }
}

/**
 * A shallow clone cannot answer "which commit added this file", so every fix
 * commit would render as unknown and `--check` would fail on a difference that
 * says nothing about the index. Fail with the cause instead of the symptom.
 */
function assertFullHistory() {
  try {
    const shallow = execFileSync('git', ['rev-parse', '--is-shallow-repository'], {
      cwd: root,
      encoding: 'utf8',
    }).trim()
    if (shallow === 'true') {
      console.error(
        'This is a shallow clone, so fix commits cannot be resolved.\n' +
          'Fetch full history (CI: actions/checkout with `fetch-depth: 0`):\n\n' +
          '  git fetch --unshallow\n',
      )
      process.exit(1)
    }
  } catch {
    /* not a git repo, or an old git: fall through and let commits read as unknown */
  }
}

assertFullHistory()

const entries = fs
  .readdirSync(auditDir)
  .filter((f) => f.endsWith('.test.ts'))
  .map((file) => {
    const m = NAME.exec(file)
    if (!m) return { file, id: '', kind: 'other', summary: '', commit: '' }
    const text = fs.readFileSync(path.join(auditDir, file), 'utf8')
    return { file, id: m[2], kind: m[1], summary: summarize(text), commit: addedIn(file) }
  })
  .sort((a, b) => a.id.localeCompare(b.id, 'en', { numeric: true }) || a.file.localeCompare(b.file))

const cell = (s) => (s || '—').replace(/\|/g, '\\|')
const link = (f) => `[\`${f}\`](./${f})`

const regressions = entries.filter((e) => e.kind === 'regression')
const probes = entries.filter((e) => e.kind === 'probe')
const other = entries.filter((e) => e.kind === 'other')

const lines = [
  '<!-- Generated by scripts/audit-index.mjs. Do not edit by hand.',
  '     Regenerate: npm run audit:index   Verify: npm run check:audit-index -->',
  '',
  '# Audit findings index',
  '',
  'What the ID in each filename under `test/audit/` refers to.',
  '',
  'The 2026-08-30 audit reported findings by ID (`A1`, `B-F2`, `G-F8`, `N3`, `O5`),',
  'and #71 landed a test per finding named after it. The reports themselves were',
  'not committed, so without this table an ID in a filename is unresolvable (#75).',
  '',
  'Every row is derived from the test file itself — its documentation comment, or',
  'its `describe` title — so this index says nothing the tests do not already say,',
  'and cannot drift from them: `check:audit-index` runs in CI.',
  '',
  '**Fix commit** is the commit that ADDED the test, which is when the finding was',
  'closed. Not necessarily the commit that changed `src/` — some findings were',
  'fixed first and pinned afterwards.',
  '',
  `## Regressions (${regressions.length})`,
  '',
  'A specific finding, and the test that keeps it fixed.',
  '',
  '| ID | Finding | Test | Fix commit |',
  '| --- | --- | --- | --- |',
  ...regressions.map((e) => `| \`${e.id}\` | ${cell(e.summary)} | ${link(e.file)} | \`${e.commit || '—'}\` |`),
  '',
  `## Probes (${probes.length})`,
  '',
  'Exploratory checks written while auditing a task area. These share a task letter',
  'rather than naming one finding, and several deliberately assert that a suspected',
  'defect is *absent*.',
  '',
  '| Task | Probe | Test |',
  '| --- | --- | --- |',
  ...probes.map((e) => `| \`${e.id}\` | ${cell(e.summary)} | ${link(e.file)} |`),
]

if (other.length) {
  lines.push(
    '',
    `## Supporting tests (${other.length})`,
    '',
    'Audit-suite tests not named after a single finding.',
    '',
    '| Test | Covers |',
    '| --- | --- |',
    ...other.map((e) => `| ${link(e.file)} | ${cell(e.summary)} |`),
  )
}

const rendered = lines.join('\n') + '\n'

if (process.argv.includes('--check')) {
  const current = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8') : ''
  if (current !== rendered) {
    console.error(
      'test/audit/README.md is out of date with test/audit/.\n' +
        'A test was added, renamed, or had its description changed.\n\n' +
        '  npm run audit:index\n',
    )
    process.exit(1)
  }
  const unresolved = entries.filter((e) => e.kind !== 'other' && !e.summary)
  if (unresolved.length) {
    console.error(
      `${unresolved.length} audit test(s) describe no finding — add a doc comment or a descriptive \`describe\` title:\n` +
        unresolved.map((e) => `  ${e.file}`).join('\n'),
    )
    process.exit(1)
  }
  console.log(`audit-index: ${entries.length} tests indexed, README.md up to date.`)
} else {
  fs.writeFileSync(outPath, rendered)
  console.log(`audit-index: wrote ${outPath} (${regressions.length} regressions, ${probes.length} probes, ${other.length} other)`)
}
